vim.cmd('colorscheme dracula')
vim.cmd('hi CursorLine guibg=#21222C')
vim.cmd('hi CursorLineNr guifg=#F1FA8C guibg=#21222C gui=none')
vim.cmd('hi IndentLine guifg=#44475a')
vim.cmd('hi DraculaErrorLine guifg=NONE guibg=NONE')
vim.cmd('hi DraculaWarnLine guifg=NONE guibg=NONE')
vim.cmd('hi DraculaInfoLine guifg=NONE guibg=NONE')
